### ISSUE TITLE
Controller to access assets

### ISSUE THREAD

**Issue by loevgaard** [thephpleague/flysystem-bundle#101]
Would it be in the scope of this bundle to have a controller you could access like `/file/{path}` which would then expose the file with the given path? If so I would love to create a PR

**Comment by tgalopin** [comment]
I thought about it as well, and my opinion is that I don't think it is:

* It's quite easy to implement manually, with much more flexibility over authorization, access control, caching, ... ;
* It's tricky to differentiate files that should be exposed and ones that shouldn't in a generic manner ;
* CDN are very often used to fit this need, with a better infrastructure to scale: I'd argue we should instead recommend to use one ;

Thus I don't think we should implement it in the bundle, but I may have forgotten something.
