### ISSUE TITLE
FilesystemOperator side effect

### ISSUE THREAD

**Issue by Radiergummi** [thephpleague/flysystem-bundle#102]
I'm injecting a `private readonly FilesystemOperator $localStorage` into one of my classes; it is configured to use a path not available on my local machine, but within a Docker container. This class is then used in a custom introspection command (showing the current pipeline configuration), which I intended to run on the local machine.

As the filesystem operator is injected into the class, and the class is in turn injected into my command instance, the operator will be instantiated, too. Unexpectedly, though, this causes the mount path to be validated, yielding an exception:

```
In UnableToCreateDirectory.php line 20:
                                                                            
  Unable to create a directory at /opt/storage. mkdir(): Permission denied  
```

I would have expected this check upon the first filesystem operation, not sooner, that is: I would strongly expect library code to not have any side effects in their constructor - just as I would never expect a database class to attempt to connect within its constructor.

I'm not quite sure yet why exactly this happens, will have to dig deeper into the code, but this feels like a bug to me. What's the rationale behind executing runtime sanity checks in the constructor?

**Comment by Radiergummi** [comment]
Hi @tgalopin,

the issue was solved in Flysystem recently, but I guess would require downstream implementation. The `LocalFilesystemAdapter` has received a new constructor argument, `bool $lazyRootCreation`, which may be set to true to defer the path check to the first operation (this is false to avoid breaking BC, but will likely be turned true in the future).

AFAIK this would require adding a new option to the local filesystem config builder in the bundle, right? If so, I'd open a PR 🙂

**Comment by tgalopin** [comment]
I'm open to a PR indeed, thanks!
