### ISSUE TITLE
MountManaget how to copy and move files to Flysystem to another one ?.

### ISSUE THREAD

**Issue by gamersalpha** [thephpleague/flysystem-bundle#105]
Hello 

i m using the bundel but i can't see how to move or copy files to flysystem to other one ?

![image](https://user-images.githubusercontent.com/32466950/176470685-e49a2f2f-21a7-4fba-8ae9-dd97baccf517.png)

can someone explain me how to copy/move files to other Flysystem please

**Comment by maxhelias** [comment]
It seems that it is now documented : https://flysystem.thephpleague.com/docs/advanced/mount-manager/

**Comment by cybernet** [comment]
should this be closed ?
