### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by ro0NL** [thephpleague/flysystem-bundle#110]
Maybe i live on the edge, but the upgrade to SFTP v3 currently is a PITA :)

```
  Missing package, to use the "sftp" adapter, run:  
                                                    
  composer require league/flysystem-sftp  
```

https://github.com/thephpleague/flysystem-bundle/compare/2.2.1...master

**Comment by tgalopin** [comment]
Done: https://github.com/thephpleague/flysystem-bundle/releases/tag/2.3.0

Thanks!
