### ISSUE TITLE
Mislead documentation?

### ISSUE THREAD

**Issue by jcornide** [thephpleague/flysystem-bundle#111]
Hi,

I recently download the bundle and I found the documentation a bit misleading. In the documentation there are a lot of references to the configuration settings in `flysystem.yaml` but the SF flex recipe creates a `oneup_flysystem.yaml` for the configuration. 

So I couldn't figure it out what exactly should be on each file. This is just me or maybe the documentation need a little update?

**Comment by tgalopin** [comment]
It seems you have installed the wrong package (one-up-flysystem is a different package).

Did you use the right Composer command?
