### ISSUE TITLE
Allow passing options to custom adapter

### ISSUE THREAD

**Issue by yellow1912** [thephpleague/flysystem-bundle#117]
At the moment, we have to create the custom adapter as a service. Lets say we use the same adapter class but with different options (similar to how aws adapter can be used with different buckets or/and prefixes), this can get messy.

I think it's relatively simple to allow pasting the class name and use that class name to initiate a new service instead. 

With PHP 8 named arguments and array spreading it should be possible to allow the user to provide the aruguments in any order https://stitcher.io/blog/php-8-named-arguments. If we do not force php8 then it's possible to just pass the whole option array and let the customer adapter handles that?

**Comment by yellow1912** [comment]
https://github.com/thephpleague/flysystem-bundle/blob/3.x/src/DependencyInjection/FlysystemExtension.php


Line 68

`$container->setAlias('flysystem.adapter.'.$storageName, $storageConfig['adapter'])->setPublic(false);`

Can be something like this (not tested)

```
if ($container->has(storageConfig['adapter'])) {
   $container->setAlias('flysystem.adapter.'.$storageName, $storageConfig['adapter'])->setPublic(false);
} else {
  // TODO: should check if storageConfig['adapter']) is a class name here
  $definition = new Definition();
  $definition->setClass(storageConfig['adapter']));
  foreach ($storageConfig['options'] as $k => $v) {
      $definition->setArgument('$' . $k, $v);
  }
  $container->setDefinition('flysystem.adapter.'.$storageName, $definition)->setPublic(false);
}
```

**Comment by yellow1912** [comment]
Hello,

I have forked this repo and applied my code as an experiment. Everything seems to work on my end. My changes allow passing either an AdapterBuilder or an Adapter class. This gives Custom Adapter much more flexibility.

https://github.com/yellow1912/flysystem-bundle/tree/develop

**Comment by maxhelias** [comment]
Hello,
What's the difference with your approach and configuring multiple storage with the same adapter as described here: [3.x/docs/5-creating-a-custom-adapter.md#using-the-adapter-in-a-storage-configuration](https://github.com/thephpleague/flysystem-bundle/blob/3.x/docs/5-creating-a-custom-adapter.md#using-the-adapter-in-a-storage-configuration) ?

**Comment by maxhelias** [comment]
A service name can be passed instead of the class, and several services can be initiated with the same class without being shared.

Note: closed due to inactivity and i didn't see any issue
