### ISSUE TITLE
Use with Supabase Storage

### ISSUE THREAD

**Issue by Snowbaha** [thephpleague/flysystem-bundle#125]
Hello,

I am searching a way to use it with [Supabase](https://github.com/supabase/supabase), I tried the AsyncAWS and AWS [methods ](https://github.com/thephpleague/flysystem-bundle/blob/3.x/docs/2-cloud-storage-providers.md#aws-sdk-s3)but it doesn't work for me.

    supabase_client:
        class: 'AsyncAws\S3\S3Client'
        arguments:
            - endpoint: 'https://MYIDFROMSUPA.supabase.co/storage/v1/object/'
              accessKeyId: 'MYIDFROMSUPA'
              accessKeySecret: '%env(SUPA_TOKEN)%'
              region: 'eu-central-1'

and

        supabase.storage.products.images:
            adapter: 'asyncaws'
            visibility: public # Make the uploaded file publicly accessible in S3
            options:
                client: 'supabase_client'
                bucket: 'products.images'

Do you have any ideas?

[I asked in their discussion too](https://github.com/supabase/supabase/discussions/11423) but it is not possible with S3 Bucket for now....

**Comment by maxhelias** [comment]
Hello,
I'm afraid you won't get a better answer here. 
This doesn't seem possible without going through Supabase.
