### ISSUE TITLE
FlysystemBundle method build must return void.

### ISSUE THREAD

**Issue by laurentmuller** [thephpleague/flysystem-bundle#145]
When using with Symfony 6.3, the following deprecation is raised:

`
1x: Method "Symfony\Component\HttpKernel\Bundle\Bundle::build()" might add "void" as a native return type declaration in the future. Do the same in child class "League\FlysystemBundle\FlysystemBundle" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in VichUploaderBundleTest::testFlysystemOfficialKernel from Vich\UploaderBundle\Tests
`

The method `build` of the class `FlysystemBundle` must add the `void` return type as follow:

```php
/**
 * {@inheritdoc}
 * 
 * @return void
 */
public function build(ContainerBuilder $container)
{
    // ...
}
```
or

```php
public function build(ContainerBuilder $container): void
{
    // ...
}
```

**Comment by Evgeny1973** [comment]
Same errors, Symfony 6.3, flysystem-bundle 3.1.0:
`Method "Symfony\Component\DependencyInjection\Extension\ExtensionInterface::load()" might add "void" as a native return type declaration in the future. Do the same in implementation "League\FlysystemBundle\DependencyInjection\FlysystemExtension" now to avoid errors or add an explicit @return annotation to suppress this message.`
`Method "Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface::process()" might add "void" as a native return type declaration in the future. Do the same in implementation "League\FlysystemBundle\DependencyInjection\Compiler\LazyFactoryPass" now to avoid errors or add an explicit @return annotation to suppress this message.`
`User Deprecated: Method "Symfony\Component\HttpKernel\Bundle\Bundle::build()" might add "void" as a native return type declaration in the future. Do the same in child class "League\FlysystemBundle\FlysystemBundle" now to avoid errors or add an explicit @return annotation to suppress this message.`

**Comment by Evgeny1973** [comment]
When is it planned to release with fixes?

**Comment by maxhelias** [comment]
I didn't see any error here, just a notice. Be patient, a PR is already open, an owner will take care of it

**Comment by Julian-Louis** [comment]
I opened a pull request (https://github.com/thephpleague/flysystem-bundle/pull/134) 4 months ago, and it still hasn't merged.
It seems that the project is no longer maintained 🫠

**Comment by Evgeny1973** [comment]
@tgalopin Hello! Can you help us with the problem of the stuck issue?

**Comment by tgalopin** [comment]
This is now merged

I just granted @maxhelias the ability to merge PR to avoid delays like this in the future
