### ISSUE TITLE
VisibilityConverter for LocalAdapter does not use directory_visbility

### ISSUE THREAD

**Issue by MHC03** [thephpleague/flysystem-bundle#148]
We had a local storage with `visibility` and `directory_visibility` as `public`. When the folder was created, it strangely had other permission than we configured in `permissions.dir.public`. Seems like the directory visibility is ignored on creation of the `PortableVisibilityConverter` [here](https://github.com/thephpleague/flysystem-bundle/blob/3.x/src/Adapter/Builder/LocalAdapterDefinitionBuilder.php#L85). This leads to the creation of nonexistent folders with the default visibility as `private`, thus a permission we did not set.

I am not sure, if that is as intended, but my suggestion would be to create the `PortableVisibilityConverter` with the given `directory_visbility`, by using it as `$defaultForDirectories`.

**Comment by maxhelias** [comment]
Indeed, with the local adapter the root folder is created by default with a private permission.
Work in progress here : https://github.com/thephpleague/flysystem-bundle/pull/139

**Comment by maxhelias** [comment]
Can you check my PR #153 pls and tell me if it's ok ?
