### ISSUE TITLE
Alternative to storing ftp/sftp password in config

### ISSUE THREAD

**Issue by bbuehrle** [thephpleague/flysystem-bundle#15]
I'm still relatively new to the Symfony game, so maybe I'm missing something and just don't know where to look.  Currently, I'm creating a project which needs to have the ability to reach out to multiple client's ftp/sftp servers.  Configuring the 20 different servers doesn't seem like it will be all that difficult (thanks to this bundle!).

My issue is that I would like to avoid putting the plain text password into a .yaml file that would be committed to my repository.  Is there a built-in option already which would allow me to store the sensitive configurations elsewhere?  My current idea would be to use doctrine and mysql for storage/retrieval, but I'm not sure how to go about injecting the storage services into the configuration.

I don't mind doing my own research, but I'm not even really sure where to begin...

**Comment by tgalopin** [comment]
Hello @bbuehrle !

You should be able to put these passwords in an environment variable that you can rely on in the YAML, thus putting the password outside of the configuration. Have a look at https://symfony.com/doc/current/configuration.html#configuration-based-on-environment-variables :) .

I never actually tried to use the bundle with env vars but they should work out of the box. If you have a problem, don't hesitate to reply here :) .

**Comment by bbuehrle** [comment]
Thanks, @tgalopin , for the fast response!

I was looking at using the environment to store the password as you've suggested.  It definitely looks like this would solve my problem, so I'll keep this in mind as a fallback solution.  But the problem with using the environment to store the passwords is that the passwords sometimes change monthly and I'll occasionally have less technical people that would need to change them or add new servers as the client-base grows.

I hate sounding as if I am dead-set on the doctrine-orm idea, but do you possibly have any other suggestions that would allow for a less static configuration?

**Comment by tgalopin** [comment]
This is something more complex indeed: what you are actually trying to build is a stateful service, a service for which the configuration can change over time without any code change. I would not recommend to put such objects inside the container and instead to put some kind of Factory in the container that you will be able to use to build these dynamically configured objects.

I don't think it would be wise to add all of this structure inside this bundle though as it's not its aim.

**Comment by bbuehrle** [comment]
I can definitely understand that, and you've pointed me in the right direction.  Thanks for all your help @tgalopin !
