### ISSUE TITLE
deprecation warnings

### ISSUE THREAD

**Issue by tacman** [thephpleague/flysystem-bundle#157]
Symfony 6.4 is almost out.

I saw these deprecation warnings when clearing the cache:

Application] Nov 22 16:51:30 |INFO   | DEPREC User Deprecated: Method "Symfony\Component\HttpKernel\Bundle\Bundle::build()" might add "void" as a native return type declaration in the future. Do the same in child class "League\FlysystemBundle\FlysystemBundle" now to avoid errors or add an explicit @return annotation to suppress this message. 
[Application] Nov 22 16:51:30 |INFO   | DEPREC User Deprecated: Method "Symfony\Component\HttpKernel\Bundle\Bundle::build()" might add "void" as a native return type declaration in the future. Do the same in child class "League\FlysystemBundle\FlysystemBundle" now to avoid errors or add an explicit @return annotation to suppress this message. 
[Application] Nov 23 11:01:12 |INFO   | DEPREC User Deprecated: Method "Symfony\Component\HttpKernel\Bundle\Bundle::build()" might add "void" as a native return type declaration in the future. Do the same in child class "League\FlysystemBundle\FlysystemBundle" now to avoid errors or add an explicit @return annotation to suppress this message. 
[Application] Nov 23 11:01:13 |INFO   | DEPREC User Deprecated: Method "Symfony\Component\HttpKernel\Bundle\Bundle::build()" might add "void" as a native return type declaration in the future. Do the same in child class "League\FlysystemBundle\FlysystemBundle" now to avoid errors or add an explicit @return annotation to suppress this message. 
[Application] Nov 23 11:01:13 |INFO   | DEPREC User Deprecated: Method "Symfony\Component\HttpKernel\Bundle\Bundle::build()" might add "void" as a native return type declaration in the future. Do the same in child class "League\FlysystemBundle\FlysystemBundle" now to avoid errors or add an explicit @return annotation to suppress this message.

**Comment by maxhelias** [comment]
Already fixed in https://github.com/thephpleague/flysystem-bundle/pull/134 and release since https://github.com/thephpleague/flysystem-bundle/releases/tag/3.2.0

**Comment by tacman** [comment]
Indeed, I had locked the bundle at ^2.4, but composer outdated didn't list this.   Odd.  But thanks, I've upgraded and indeed it's working!
