### ISSUE TITLE
[Maintenance] Remove outdated SF mention at GH and packagist repo description 

### ISSUE THREAD

**Issue by diimpp** [thephpleague/flysystem-bundle#168]
Mention of outdated versions makes feel as bundle itself is outdated, which is not true.

GH repo description
```patch
--- Symfony bundle integrating Flysystem into Symfony 4.2+ applications 
+++ Symfony bundle integrating Flysystem into Symfony applications 
```

Packagist/composer [package description](https://github.com/thephpleague/flysystem-bundle/blob/6a74baa0ba3eb7ce01459e3beff5586ca007a830/composer.json#L3)
```patch
--- Symfony bundle integrating Flysystem into Symfony 5.4+ applications
+++ Symfony bundle integrating Flysystem into Symfony applications
```

![image](https://github.com/user-attachments/assets/05d5d1b9-1b10-40f0-a251-b8ce52ec7147)
![image](https://github.com/user-attachments/assets/57beaa35-1760-43c7-8c29-de0f507c7ef9)

**Comment by maxhelias** [comment]
@tgalopin I updated the composer.json here : https://github.com/thephpleague/flysystem-bundle/pull/169 but I don't have the permissions to do that on the repo, can you?

**Comment by tgalopin** [comment]
Done, good idea!
