### ISSUE TITLE
Cannot set "directoryPerm" option on sftp adapter

### ISSUE THREAD

**Issue by chaniwat** [thephpleague/flysystem-bundle#17]
When add option to sftp adapter, its say:
`The option "directoryPerm" does not exist. Defined options are: "host", "password", "port", "private_key", "root", "timeout", "username".`

I think the problem is in [`\League\FlysystemBundle\Adapter\Builder\SftpAdapterDefinitionBuilder::configureOptions()`](https://github.com/thephpleague/flysystem-bundle/blob/cdd73c825031a5330f184f4ce73200211e426df2/src/Adapter/Builder/SftpAdapterDefinitionBuilder.php#L37-L59) because there is no `directoryPerm` set allow type to `OptionsResolver`

**Comment by tgalopin** [comment]
Hello @chaniwat !

When I wrote this bundle I actually used the documentation of Flysystem ... which lacks this parameter (https://flysystem.thephpleague.com/docs/adapter/sftp/)! 

This already happened in the past with the FTP adapter: https://github.com/thephpleague/flysystem-bundle/pull/12. If you want to open a PR for the directoryPerm option, I'd be happy to help you :) .

You can also create a PR on the doc to add the configuration option if you want (like https://github.com/thephpleague/flysystem/pull/1028).
