### ISSUE TITLE
Service ids should be prefixed

### ISSUE THREAD

**Issue by stof** [thephpleague/flysystem-bundle#2]
Currently, the storage gets stored as a service id equal to the storage name you provide. This is very likely to create conflicts with ids of other bundles.
The id should instead be prefixed with `flysystem.storage.` instead, to avoid conflicts in the container.

**Comment by nicolas-grekas** [comment]
Like cache pools/messenger buses, adding hidden conventions managed by bundles is better avoided.
That's why I recommended doing it this way.

**Comment by stof** [comment]
Well, the best practice for shared bundles is to prefix services it defines, to avoid conflicts. That's true since years.

Expecting everyone to be careful that storage names in one bundle must not conflict with any service id elsewhere makes users responsible for any WTF moment they have.

anyway, the recommended usage of this bundle seems to be using named autowiring aliases, and these are fine without the flysystem prefix (as they are already namespaced by the interface itself).

**Comment by tgalopin** [comment]
I suggest we consider this for 2.0 only if the problem arise often in 1.0 (I doubt it will). I'll keep this issue open so that people can tell here if they have troubles with this.
