### ISSUE TITLE
How this bundle differs from OneupFlysystemBundle

### ISSUE THREAD

**Issue by danaki** [thephpleague/flysystem-bundle#20]
A note in README would be appreciated.

**Comment by stephanvierkant** [comment]
What a shame! Creating a new bundle that does exactly the same as an existing well-maintained, widely used bundle and not a single comment about it.

Is this really an example of [NIH syndrome](https://en.wikipedia.org/wiki/Not_invented_here)?

I don't see why this bundle adds any value, other than splitting up the community.

**Comment by tgalopin** [comment]
Have you had a look at the implementation?
