### ISSUE TITLE
Failure connecting using SFTP adapter with private key

### ISSUE THREAD

**Issue by bretrzaun** [thephpleague/flysystem-bundle#26]
Hello,
I am trying to store files using the SFTP adapter.
Everything works great as long I am using password authentication.
But when using a private key I get the error message: "Could not login with username: xxx, host: yyy".

After doing a bit of research in the source code I think I might have found the problem:
According to the SFTP adapters documentation (https://flysystem.thephpleague.com/docs/adapter/sftp/) the private key option is called "privateKey". However in the bundle configuration I am forced to use "private_key" and as far as I can see this option is given to the adapter directly. I believe this results in no private key being passed.

**Comment by tgalopin** [comment]
Hello @bretrzaun !

That may well be a bug indeed. Could you try to update the code in your vendor and check if it works by changing this option name?

**Comment by bretrzaun** [comment]
Hello @tgalopin,
already did! And from what my debugging shows it looks much better. However - I cannot be completely sure since I locked the only test account I have and need to wait for it to be unlocked from IT. 
But at least the SFTP adapter instance now has the private key property set...

**Comment by bretrzaun** [comment]
Now I can confirm renaming the options makes things work with using private key.

**Comment by bretrzaun** [comment]
created a pull request: #27
