### ISSUE TITLE
A name for each instance ?

### ISSUE THREAD

**Issue by johndodev** [thephpleague/flysystem-bundle#30]
Hello,

If I want to make a storage registry to be able to get one dynamically, I see no way to do it. The tag flysystem.storage allow me to get an iterable, but I don't know which storages they are.

Is there a way to achieve that ? I could do it if each instance had a name (like the name of the service).

Last option I see is to make all storages public and inject the container to my registry, which is crappy.

**Comment by johndodev** [comment]
A compiler pass do the job, but maybe you can consider a name anyway.

**Comment by tgalopin** [comment]
Perhaps having a service locator using indexed tagged services (https://symfony.com/blog/new-in-symfony-4-3-indexed-and-tagged-service-collections) would work?

**Comment by johndodev** [comment]
Oh it seems really interesting ! I took a look and it seems I still need to do a compilerPass but I can build a serviceLocator. 
Or I can write a compilerPass just to add a property "name" to the "flysystem.storage" tag and use it to generate a serviceLocator with a notation like 
```yaml
    arguments: [!tagged_locator { tag: 'flysystem.storage', index_by: 'name' }]
```

Maybe we could do that in this line : 
https://github.com/thephpleague/flysystem-bundle/blob/master/src/DependencyInjection/FlysystemExtension.php#L70 

```php
// before
$definition->addTag('flysystem.storage');

// after (the $storageName should be send in the function)
$definition->addTag('flysystem.storage', ['name' => $storageName]));
```
I will try some stuff, thanks !

**Comment by tgalopin** [comment]
`$definition->addTag('flysystem.storage', ['name' => $storageName]));` is what I had in mind, yes. If you want to open a PR for that, I'd be happy to review it :) !

**Comment by tgalopin** [comment]
Ah and you can't use `name` as an index, it's already used by the tag system. I think `storage` would be a nice name :) .
