### ISSUE TITLE
Error Google Cloud Storage

### ISSUE THREAD

**Issue by edgargalvezr** [thephpleague/flysystem-bundle#46]
Hello, I have configured flysystem-bundle in Symfony 5, also in Google Storage, but I have the following error:
`{
"error": {
"code": 401,
"message": "Invalid Credentials",
"errors": [
{
"message": "Invalid Credentials",
"domain": "global",
"reason": "authError",
"locationType": "header",
"location": "Authorization"
}
]
}
}
\vendor\google\cloud-core\src\RequestWrapper.php (line 362)`

`flysystem:
    storages:
        default.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/storage/default'

        gcs.storage:
            adapter: 'gcloud'
            options:
                client: 'gcloud_client_service' # The service ID of the Google\Cloud\Storage\StorageClient instance
                bucket: 'test-storage'
                #prefix: 'optional/path/prefix'
                api_url: 'https://storage.googleapis.com'`

`gcloud_client_service:
        class: Google\Cloud\Storage\StorageClient
        arguments:
            - projectId: 'academico-214422'
            - keyFilePath: '../credentials333.json'`

Help me

**Comment by tgalopin** [comment]
Hello,

Did you use the documentation of the library handling this storage to configure your client? (have a look at https://github.com/Superbalist/flysystem-google-cloud-storage if you didn't :) )
