### ISSUE TITLE
Do not require whole framework bundle

### ISSUE THREAD

**Issue by JarJak** [thephpleague/flysystem-bundle#5]
Maybe this bundle needs only a couple of components? Look how this bundle is dealing with it: https://github.com/1up-lab/OneupFlysystemBundle/blob/master/composer.json

**Comment by tgalopin** [comment]
Hello JarJak,

Thanks for the feedback.

I'm not sure to understand what you mean :) . All the bundles I know require the framework-bundle, including the one you linked. What would be useful in not requiring the whole framework-bundle?

**Comment by JarJak** [comment]
Oh sorry, my mistake :)

**Comment by Taluu** [comment]
The framework-bundle doesn't look like it is used anywhere. So IMO it should be removed from the require section (as a dev requirement, maybe if there are some tests that requires it ? I doubt so).

If we need to use this bundle while having an unsupported version of the fw-bundle (e.g, a bundle from the past or too far in the future, a dev requirement on the fw-bundle, ... and so on), we will be prevented from installing this package.

This is really a constraint for something that shouldn't be there. And no, all bundles does not require the fw-bundle. Instead, you should split this dependency *into the components you really need*.

But that's only my opinion...

**Comment by tgalopin** [comment]
Can you do a PR @Taluu? That would the best to explore the idea.

Thanks!

**Comment by JarJak** [comment]
> What would be useful in not requiring the whole framework-bundle?

It is very useful if your project depends only on couple of Symfony components.

**Comment by tgalopin** [comment]
But then, you would need to use the HttpKernel and wire everything yourself without the Framework bundle. That's a lot work and I'm not sure many people do this. You can easily use the library without the bundle if you don't use Symfony HttpKernel :).

I'm still open to PRs of course to discuss this idea!

**Comment by Taluu** [comment]
You don't have to wire anything with or without the fw bundle...

**Comment by JarJak** [comment]
You don't have to wire anything since Symfony Flex

**Comment by tgalopin** [comment]
I'm ready to discuss this with a PR. I still don't really think this is a huge use case, but if you feel this is a good improvement, I'd be happy to discuss the PR :).

**Comment by tgalopin** [comment]
I started to work on https://github.com/thephpleague/flysystem-bundle/pull/9, I think this is what you have in mind?

**Comment by JarJak** [comment]
@tgalopin looks good to me!
