### ISSUE TITLE
Could not load package ezsystems/ezplatform

### ISSUE THREAD

**Issue by shubaivan** [thephpleague/flysystem-bundle#51]
I use symfony/framework-bundle v5.0.5 in docker-compose. And when I try executed `composer require league/flysystem-bundle` I faced wth that:

```
  [RuntimeException]                                                           
  Could not load package ezsystems/ezplatform in http://repo.packagist.org: [  
  UnexpectedValueException] Could not parse version constraint dev-load-varni  
  sh-only-when-used as ^2.0@dev: Invalid version string "^2.0@dev"             
  [UnexpectedValueException]                                                   
  Could not parse version constraint dev-load-varnish-only-when-used as ^2.0@  
  dev: Invalid version string "^2.0@dev"  
```

what I'm doing wrong or what need to do ?

**Comment by tgalopin** [comment]
Hello,

It doesn't seem to be a problem related to flysystem-bundle but to your composer.json file instead: you seem to have added a package version for `ezsystems/ezplatform` which is invalid. I suggest you change the version for `^2.0` and retry!

**Comment by shubaivan** [comment]
problem was with new composer version 1.10.11. I reduced to 1.10.10 and bundle installed
