### ISSUE TITLE
Support league/flysystem-aws-s3-v2

### ISSUE THREAD

**Issue by michaelKaefer** [thephpleague/flysystem-bundle#55]
To use the S3 compatible Exoscale instead of AWS S3 we need to use `league/flysystem-aws-s3-v2` instead of `league/flysystem-aws-s3-v2`.

No version of your bundle does support v2 but only v3 - or is that wrong? Do you plan to support it or do we have to switch to `oneup/flysystem-bundle`?

**Comment by tgalopin** [comment]
Hi!

Have you considered using AsyncAWS instead? https://async-aws.com/

It may fit your need (https://github.com/thephpleague/flysystem-bundle/blob/master/docs/2-cloud-storage-providers.md#asyncaws-s3)

**Comment by michaelKaefer** [comment]
Sorry for the issue, I was wrong: your bundle and `league/flysystem-aws-s3-v2` work fine with Exoscale.
