### ISSUE TITLE
Release changes from 1.x branch

### ISSUE THREAD

**Issue by vhenzl** [thephpleague/flysystem-bundle#77]
Would it be possible to release a new version from 1.x branch, please? There are more unreleased changes, but the most important is #64, which makes the bundle compatible with `async-aws/flysystem-s3` [v1.0](https://github.com/async-aws/flysystem-s3/blob/1.0.0/CHANGELOG.md#100). Thanks!

**Comment by tgalopin** [comment]
Released (a bit late I agree ;) )

https://github.com/thephpleague/flysystem-bundle/releases/tag/1.6.0
