### ISSUE TITLE
How to access files in front

### ISSUE THREAD

**Issue by mathvicot15** [thephpleague/flysystem-bundle#80]
Hello,

I'm using Flysystem-bundle with local and s3 (scaleway) adapter.

I can't seem to find any examples or documentation that demonstrates how to access files (view / download) in the front, with twig for my case.

Am I doing it wrong or is it a use that is not intended with the fly system ?

**Comment by terox** [comment]
I think that purpose of that library is only write/read/list... not what should do after that.

In any case, the final statement if fetch the "file". Maybe this could help:
https://symfony.com/doc/current/components/http_foundation.html#serving-files

Cheers

**Comment by mathvicot15** [comment]
Hello,

Thanks for your response, I found a solution after publishing this comment but i forgot to close it. 

My apologies.
