### ISSUE TITLE
Symfony 6 compatibility

### ISSUE THREAD

**Issue by vuryss** [thephpleague/flysystem-bundle#85]
Now that we have Symfony 6 officially released, I hope the bundle can be adjusted to support it.

**Comment by MichaelBrauner** [comment]
This would be really nice!

**Comment by tgalopin** [comment]
There is a PR already: https://github.com/thephpleague/flysystem-bundle/pull/84

I'd prefer to give @AbdelilahJabri a bit of time to finalize it if he can, but otherwise I'll do it, no worry :) .

**Comment by tgalopin** [comment]
I just merged the PR and will release soon.
