### ISSUE TITLE
Symfony 5 - Update the bundel

### ISSUE THREAD

**Issue by gamersalpha** [thephpleague/flysystem-bundle#89]
Hello evrybody, before i test the bundel can u tell me if the bundel is still updated and maintenaind please

**Comment by tgalopin** [comment]
Yes it is maintained: you can see indicators of that by checking the latest commits (https://github.com/thephpleague/flysystem-bundle/commits/master), releases (https://github.com/thephpleague/flysystem-bundle/releases), ...
