### ISSUE TITLE
Update docs to reflect Flysystem 3

### ISSUE THREAD

**Issue by tacman** [thephpleague/flysystem-bundle#90]
Can you update the docs to reflect that this bundle also works with Flysystem 3 (only BC break was custom adapters).

I've also requested that the flysystem repo reflect that versions 2 and 3 are not in beta anymore.

https://github.com/thephpleague/flysystem/issues/1419

This will help people who are just getting started.  Thanks.

**Comment by stof** [comment]
This should be closed as #91 was merged.
