### ISSUE TITLE
Drop support for dependencies in EOL

### ISSUE THREAD

**Issue by tacman** [thephpleague/flysystem-bundle#92]
I think this bundle should require PHP 7.4 or PHP 8.x, Symfony 4.4, 5.4 or 6.x.

I can make this change and run tests and submit a PR if you agree.

**Comment by tgalopin** [comment]
For the moment, I don't feel a maintenance burden on supporting Symfony 4.2+ and PHP 7.2+. I'm generally not in favor of introducing artificial constraints (ie constraints that are not technically relevant) to Composer versions. Do you have a specific reason you'd like to do this?

**Comment by maxhelias** [comment]
Done here : https://github.com/thephpleague/flysystem-bundle/pull/115
