### ISSUE TITLE
Add support for AWS pre-signed URL

### ISSUE THREAD

**Issue by Alg1d** [thephpleague/flysystem-bundle#98]
Add ability to get the pre-signed URL to an Amazon S3 object by using the `Aws\S3\S3Client::createPresignedRequest()` method. More details can be found in [AWS documentation](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/s3-presigned-url.html).

**Comment by maxhelias** [comment]
See my response on https://github.com/thephpleague/flysystem-aws-s3-v3/issues/296

**Comment by dkarlovi** [comment]
See https://github.com/thephpleague/flysystem/issues/1587

**Comment by maxhelias** [comment]
This can be done using the `temporaryUrl` method, see : https://flysystem.thephpleague.com/docs/usage/temporary-urls/
There's no need to do anything here.
